//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValidationMessage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EtaskMinstry.Resources.Shared.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مطابق.
        /// </summary>
        public static string CompareValidator {
            get {
                return ResourceManager.GetString("CompareValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال كود بلد صحيح .
        /// </summary>
        public static string countrycodevalid {
            get {
                return ResourceManager.GetString("countrycodevalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يسمح بأستخدام رموز خاصة.
        /// </summary>
        public static string DenaySpecialChar {
            get {
                return ResourceManager.GetString("DenaySpecialChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذه البيانات تم ادخالها مسبقا.
        /// </summary>
        public static string DublicatedItem {
            get {
                return ResourceManager.GetString("DublicatedItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل رقم (مثل 123,45).
        /// </summary>
        public static string ExpectedTime {
            get {
                return ResourceManager.GetString("ExpectedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب فيس بوك غير صحيح.
        /// </summary>
        public static string FaceBook {
            get {
                return ResourceManager.GetString("FaceBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب جوجل غير صحيح.
        /// </summary>
        public static string GooglePlus {
            get {
                return ResourceManager.GetString("GooglePlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابعاد الصوره غير مطابقة.
        /// </summary>
        public static string InValidImageSize {
            get {
                return ResourceManager.GetString("InValidImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يقل عدد الارقام عن 10 ارقام.
        /// </summary>
        public static string Length10 {
            get {
                return ResourceManager.GetString("Length10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الارقام عن 15 رقم.
        /// </summary>
        public static string Length15 {
            get {
                return ResourceManager.GetString("Length15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 150 حرف.
        /// </summary>
        public static string Length150 {
            get {
                return ResourceManager.GetString("Length150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لايقل عدد الحروف عن 5 احرف.
        /// </summary>
        public static string Length5 {
            get {
                return ResourceManager.GetString("Length5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 50حرف.
        /// </summary>
        public static string Length50 {
            get {
                return ResourceManager.GetString("Length50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إختيار ملف أكبر من 500 ميجا . .
        /// </summary>
        public static string MediaSize {
            get {
                return ResourceManager.GetString("MediaSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  نوع الملف غير صحيح ..
        /// </summary>
        public static string MediaType {
            get {
                return ResourceManager.GetString("MediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لايوجد بيانات حاليا.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال ارقام فقط.
        /// </summary>
        public static string NumbersOnly {
            get {
                return ResourceManager.GetString("NumbersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان يتراوح رقم البورت مابين 0 و 65535.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار ملف السيرة الذاتية.
        /// </summary>
        public static string RequiredFile {
            get {
                return ResourceManager.GetString("RequiredFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب تويتر غير صحيح.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عن 13 رقم و لا يقل عن 10 أرقام.
        /// </summary>
        public static string ValidateMobile {
            get {
                return ResourceManager.GetString("ValidateMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن لا تترك  التعليق فارغ . .
        /// </summary>
        public static string ValidCommentRequired {
            get {
                return ResourceManager.GetString("ValidCommentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار منطقة المسجد ..
        /// </summary>
        public static string ValidComparerAreaddl {
            get {
                return ResourceManager.GetString("ValidComparerAreaddl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار قسم للمقاله ..
        /// </summary>
        public static string ValidComparerCategoryddl {
            get {
                return ResourceManager.GetString("ValidComparerCategoryddl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمه السر غير متطابقه ..
        /// </summary>
        public static string ValidComparerPassword {
            get {
                return ResourceManager.GetString("ValidComparerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار قمر للقناه ..
        /// </summary>
        public static string ValidComparerSatddl {
            get {
                return ResourceManager.GetString("ValidComparerSatddl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متاكد انك تريد الحذف ؟ ..
        /// </summary>
        public static string ValidDelete {
            get {
                return ResourceManager.GetString("ValidDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن لا تترك  البريد الإلكتروني فارغ ..
        /// </summary>
        public static string ValidEmailRequired {
            get {
                return ResourceManager.GetString("ValidEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم تتم العمليه بنجاح ..
        /// </summary>
        public static string ValidFailure {
            get {
                return ResourceManager.GetString("ValidFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال رقم جوال صحيح.
        /// </summary>
        public static string ValidJawal {
            get {
                return ResourceManager.GetString("ValidJawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  كلمة السر يجب ان تكون بين 4 و 8 حروف أو أرقام و تشمل ما لا يقل عن رقم واحد.
        /// </summary>
        public static string ValidPassword {
            get {
                return ResourceManager.GetString("ValidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء إدخال رقم هاتف صحيح.
        /// </summary>
        public static string ValidPhoneNo {
            get {
                return ResourceManager.GetString("ValidPhoneNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير مسموح بكتابه رموز خاصه ..
        /// </summary>
        public static string ValidRegulaDetail {
            get {
                return ResourceManager.GetString("ValidRegulaDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 1000حرف أو يقل عن 240حرف و غير مسموح بكتابه رموز خاصه ..
        /// </summary>
        public static string ValidRegularDescriptionChannel {
            get {
                return ResourceManager.GetString("ValidRegularDescriptionChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 1000حرف أو يقل عن 240حرف و غير مسموح بكتابه رموز خاصه ..
        /// </summary>
        public static string ValidRegularDescriptionInterviewer {
            get {
                return ResourceManager.GetString("ValidRegularDescriptionInterviewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 1000حرف أو يقل عن 240 حرف و غير مسموح بكتابه رموز خاصه ..
        /// </summary>
        public static string ValidRegularDescriptionProgram {
            get {
                return ResourceManager.GetString("ValidRegularDescriptionProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بريد الكترونى غير صحيح ..
        /// </summary>
        public static string ValidRegularEmail {
            get {
                return ResourceManager.GetString("ValidRegularEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 100 حرف و غير مسموح بكتابه رموز خاصه ..
        /// </summary>
        public static string ValidRegularFullName100 {
            get {
                return ResourceManager.GetString("ValidRegularFullName100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 150 حرف و غير مسموح بكتابه رموز خاصه ..
        /// </summary>
        public static string ValidRegularFullName150 {
            get {
                return ResourceManager.GetString("ValidRegularFullName150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 250 حرف و غير مسموح بكتابه رموز خاصه..
        /// </summary>
        public static string ValidRegularFullName250 {
            get {
                return ResourceManager.GetString("ValidRegularFullName250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 450 حرف و غير مسموح بكتابه رموز خاصه ..
        /// </summary>
        public static string ValidRegularFullName450 {
            get {
                return ResourceManager.GetString("ValidRegularFullName450", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 50 حرف و غير مسموح بكتابه رموز خاصه ..
        /// </summary>
        public static string ValidRegularFullName50 {
            get {
                return ResourceManager.GetString("ValidRegularFullName50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 10 حرف و غير مسموح بكتابه رموز خاصه ..
        /// </summary>
        public static string ValidRegularName10 {
            get {
                return ResourceManager.GetString("ValidRegularName10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 15 حرف و غير مسموح بكتابه رموز خاصه ..
        /// </summary>
        public static string ValidRegularName15 {
            get {
                return ResourceManager.GetString("ValidRegularName15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عن 15 رقم و لا يقل عن 11 رقم ..
        /// </summary>
        public static string ValidRegularPhone {
            get {
                return ResourceManager.GetString("ValidRegularPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 180 حرف و غير مسموح بكتابه رموز خاصه ..
        /// </summary>
        public static string ValidRegularSummary180 {
            get {
                return ResourceManager.GetString("ValidRegularSummary180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 200 حرف و غير مسموح بكتابه رموز خاصه ..
        /// </summary>
        public static string ValidRegularSummary200 {
            get {
                return ResourceManager.GetString("ValidRegularSummary200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 2000 حرف و غير مسموح بكتابه رموز خاصه ..
        /// </summary>
        public static string ValidRegularSummary2000 {
            get {
                return ResourceManager.GetString("ValidRegularSummary2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 300 حرف و غير مسموح بكتابه رموز خاصه ..
        /// </summary>
        public static string ValidRegularSummary300 {
            get {
                return ResourceManager.GetString("ValidRegularSummary300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 350 حرف و غير مسموح بكتابه رموز خاصه ..
        /// </summary>
        public static string ValidRegularSummary350 {
            get {
                return ResourceManager.GetString("ValidRegularSummary350", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 500 حرف و غير مسموح بكتابه رموز خاصه ..
        /// </summary>
        public static string ValidRegularSummary500 {
            get {
                return ResourceManager.GetString("ValidRegularSummary500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 600 حرف و غير مسموح بكتابه رموز خاصه ..
        /// </summary>
        public static string ValidRegularSummary600 {
            get {
                return ResourceManager.GetString("ValidRegularSummary600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 120حرف أو يقل عن 80 حرف و غير مسموح بكتابه رموز خاصه ..
        /// </summary>
        public static string ValidRegularSummaryProgram {
            get {
                return ResourceManager.GetString("ValidRegularSummaryProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 20 حرف و غير مسموح بكتابه رموز خاصه ..
        /// </summary>
        public static string ValidRegulaTitler20 {
            get {
                return ResourceManager.GetString("ValidRegulaTitler20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 40 حرف و غير مسموح بكتابه رموز خاصه ..
        /// </summary>
        public static string ValidRegulaTitler40 {
            get {
                return ResourceManager.GetString("ValidRegulaTitler40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 50 حرف و غير مسموح بكتابه رموز خاصه ..
        /// </summary>
        public static string ValidRegulaTitler50 {
            get {
                return ResourceManager.GetString("ValidRegulaTitler50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور غير متطابقة.
        /// </summary>
        public static string ValidRepeatPassword {
            get {
                return ResourceManager.GetString("ValidRepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن لا تترك  الخانات فارغة.
        /// </summary>
        public static string ValidRequired {
            get {
                return ResourceManager.GetString("ValidRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string ValidRequiredwithBR {
            get {
                return ResourceManager.GetString("ValidRequiredwithBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تمت العمليه بنجاح ..
        /// </summary>
        public static string ValidSuccess {
            get {
                return ResourceManager.GetString("ValidSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال ملف فلاش.
        /// </summary>
        public static string ValidSWFFile {
            get {
                return ResourceManager.GetString("ValidSWFFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن لا تترك  العنوان فارغ ..
        /// </summary>
        public static string ValidTitleRequired {
            get {
                return ResourceManager.GetString("ValidTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل الرابط بشكل صحيح مثال http://www.mysite.com ..
        /// </summary>
        public static string ValidUrl {
            get {
                return ResourceManager.GetString("ValidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء أدخال سعر مناسب.
        /// </summary>
        public static string ValiedCurrency {
            get {
                return ResourceManager.GetString("ValiedCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 150 حرف ..
        /// </summary>
        public static string Valiedmax150 {
            get {
                return ResourceManager.GetString("Valiedmax150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الخانات عن 20.
        /// </summary>
        public static string Valiedmax20 {
            get {
                return ResourceManager.GetString("Valiedmax20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 250 حرف ..
        /// </summary>
        public static string Valiedmax250 {
            get {
                return ResourceManager.GetString("Valiedmax250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا يزيد عدد الحروف عن 50 حرف ..
        /// </summary>
        public static string Valiedmax50 {
            get {
                return ResourceManager.GetString("Valiedmax50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء أدخال رقم موجب.
        /// </summary>
        public static string ValiedNumber {
            get {
                return ResourceManager.GetString("ValiedNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار نوع الهاتف..
        /// </summary>
        public static string ValiedPhoneType {
            get {
                return ResourceManager.GetString("ValiedPhoneType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان تكتب راقم لا يزيد عن 1024 ولا يقل عن 0.
        /// </summary>
        public static string ValiedRange {
            get {
                return ResourceManager.GetString("ValiedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء أدخال رقم بين 0 الى 10.
        /// </summary>
        public static string ValiedRange10 {
            get {
                return ResourceManager.GetString("ValiedRange10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برجاء إدخال رقم هاتف صحيح.
        /// </summary>
        public static string vrPhone {
            get {
                return ResourceManager.GetString("vrPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب يوتيوب غير صحيح.
        /// </summary>
        public static string YouTube {
            get {
                return ResourceManager.GetString("YouTube", resourceCulture);
            }
        }
       
    }
}
