//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QvApi.Test.Etask {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Evaluation", Namespace="http://schemas.datacontract.org/2004/07/QvApi.Entities")]
    [System.SerializableAttribute()]
    public partial class Evaluation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ActivityLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AssignedTasksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompletedTasksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstLaborOfficeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstSequenceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LoginCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LogoutCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalWorkTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ActivityLevel {
            get {
                return this.ActivityLevelField;
            }
            set {
                if ((this.ActivityLevelField.Equals(value) != true)) {
                    this.ActivityLevelField = value;
                    this.RaisePropertyChanged("ActivityLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AssignedTasks {
            get {
                return this.AssignedTasksField;
            }
            set {
                if ((this.AssignedTasksField.Equals(value) != true)) {
                    this.AssignedTasksField = value;
                    this.RaisePropertyChanged("AssignedTasks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompletedTasks {
            get {
                return this.CompletedTasksField;
            }
            set {
                if ((this.CompletedTasksField.Equals(value) != true)) {
                    this.CompletedTasksField = value;
                    this.RaisePropertyChanged("CompletedTasks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstLaborOfficeId {
            get {
                return this.EstLaborOfficeIdField;
            }
            set {
                if ((this.EstLaborOfficeIdField.Equals(value) != true)) {
                    this.EstLaborOfficeIdField = value;
                    this.RaisePropertyChanged("EstLaborOfficeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstSequenceNumber {
            get {
                return this.EstSequenceNumberField;
            }
            set {
                if ((this.EstSequenceNumberField.Equals(value) != true)) {
                    this.EstSequenceNumberField = value;
                    this.RaisePropertyChanged("EstSequenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IdNumber {
            get {
                return this.IdNumberField;
            }
            set {
                if ((this.IdNumberField.Equals(value) != true)) {
                    this.IdNumberField = value;
                    this.RaisePropertyChanged("IdNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LoginCount {
            get {
                return this.LoginCountField;
            }
            set {
                if ((this.LoginCountField.Equals(value) != true)) {
                    this.LoginCountField = value;
                    this.RaisePropertyChanged("LoginCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LogoutCount {
            get {
                return this.LogoutCountField;
            }
            set {
                if ((this.LogoutCountField.Equals(value) != true)) {
                    this.LogoutCountField = value;
                    this.RaisePropertyChanged("LogoutCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalWorkTime {
            get {
                return this.TotalWorkTimeField;
            }
            set {
                if ((this.TotalWorkTimeField.Equals(value) != true)) {
                    this.TotalWorkTimeField = value;
                    this.RaisePropertyChanged("TotalWorkTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Etask.IEtask")]
    public interface IEtask {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEtask/GetTeleworkersEvaluation", ReplyAction="http://tempuri.org/IEtask/GetTeleworkersEvaluationResponse")]
        QvApi.Test.Etask.Evaluation[] GetTeleworkersEvaluation(System.DateTime PeriodStart, System.DateTime PeriodEnd, string ClientReference);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEtask/GetTeleworkersEvaluation", ReplyAction="http://tempuri.org/IEtask/GetTeleworkersEvaluationResponse")]
        System.Threading.Tasks.Task<QvApi.Test.Etask.Evaluation[]> GetTeleworkersEvaluationAsync(System.DateTime PeriodStart, System.DateTime PeriodEnd, string ClientReference);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEtaskChannel : QvApi.Test.Etask.IEtask, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EtaskClient : System.ServiceModel.ClientBase<QvApi.Test.Etask.IEtask>, QvApi.Test.Etask.IEtask {
        
        public EtaskClient() {
        }
        
        public EtaskClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EtaskClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EtaskClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EtaskClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public QvApi.Test.Etask.Evaluation[] GetTeleworkersEvaluation(System.DateTime PeriodStart, System.DateTime PeriodEnd, string ClientReference) {
            return base.Channel.GetTeleworkersEvaluation(PeriodStart, PeriodEnd, ClientReference);
        }
        
        public System.Threading.Tasks.Task<QvApi.Test.Etask.Evaluation[]> GetTeleworkersEvaluationAsync(System.DateTime PeriodStart, System.DateTime PeriodEnd, string ClientReference) {
            return base.Channel.GetTeleworkersEvaluationAsync(PeriodStart, PeriodEnd, ClientReference);
        }
    }
}
