//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int AttachmentID { get; set; }
        public string FileName { get; set; }
        public string Description { get; set; }
        public string OriginalFileName { get; set; }
        public Nullable<int> TaskID { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
