//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentStatu
    {
        public CommentStatu()
        {
            this.TaskComments = new HashSet<TaskComment>();
        }
    
        public int CommentStatusID { get; set; }
        public string CommentStatus { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<TaskComment> TaskComments { get; set; }
    }
}
