//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.HoliDays = new HashSet<HoliDay>();
            this.LogGenerals = new HashSet<LogGeneral>();
            this.Projects = new HashSet<Project>();
            this.Tasks = new HashSet<Task>();
            this.WeekEnds = new HashSet<WeekEnd>();
            this.Employees = new HashSet<Employee>();
            this.UserAccounts = new HashSet<UserAccount>();
        }
    
        public int CompanyID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string CommercialRegister { get; set; }
        public string Logo { get; set; }
        public Nullable<int> LaborOfficeID { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public Nullable<bool> HasAttendanceReport { get; set; }
        public Nullable<bool> BriefTaskReport { get; set; }
    
        public virtual ICollection<HoliDay> HoliDays { get; set; }
        public virtual ICollection<LogGeneral> LogGenerals { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<WeekEnd> WeekEnds { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<UserAccount> UserAccounts { get; set; }
    }
}
