//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Attendances = new HashSet<Attendance>();
            this.LogGenerals = new HashSet<LogGeneral>();
            this.Tasks = new HashSet<Task>();
            this.TaskComments = new HashSet<TaskComment>();
            this.UserAccounts = new HashSet<UserAccount>();
        }
    
        public int EmpID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string JobTitle { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> LaborOfficeID { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public string NationalID { get; set; }
        public string ImageName { get; set; }
        public string NationaIDImage { get; set; }
    
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual Company Company { get; set; }
        public virtual ICollection<LogGeneral> LogGenerals { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<TaskComment> TaskComments { get; set; }
        public virtual ICollection<UserAccount> UserAccounts { get; set; }
    }
}
