//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class EtaskMinstryEntities : DbContext
    {
        public EtaskMinstryEntities()
                : base("name=EtaskMinstryEntities")
        {
        }
        public EtaskMinstryEntities(string connectionstring)
: base(connectionstring)
        {
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 580;

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Attachment> Attachments { get; set; }
        public DbSet<CommentStatu> CommentStatus { get; set; }
        public DbSet<ControllerName> ControllerNames { get; set; }
        public DbSet<HoliDay> HoliDays { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<Notification> Notifications { get; set; }
        public DbSet<NotificationCollection> NotificationCollections { get; set; }
        public DbSet<NotificationType> NotificationTypes { get; set; }
        public DbSet<Priority> Priorities { get; set; }
        public DbSet<RecurrenceTask> RecurrenceTasks { get; set; }
        public DbSet<RecurrenceTaskEmp> RecurrenceTaskEmps { get; set; }
        public DbSet<RecurrenceType> RecurrenceTypes { get; set; }
        public DbSet<Setting> Settings { get; set; }
        public DbSet<SIGNAL_R_SESSION> SIGNAL_R_SESSION { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<Task> Tasks { get; set; }
        public DbSet<TaskComment> TaskComments { get; set; }
        public DbSet<TaskLog> TaskLogs { get; set; }
        public DbSet<TaskTLog> TaskTLogs { get; set; }
        public DbSet<UserType> UserTypes { get; set; }
        public DbSet<WeekEnd> WeekEnds { get; set; }
        public DbSet<TotalLog> TotalLogs { get; set; }
        public DbSet<Project> Projects { get; set; }
        public DbSet<LogGeneral> LogGenerals { get; set; }
        public DbSet<ContactU> ContactUs { get; set; }
        public DbSet<TimeUnit> TimeUnits { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<Attendance> Attendances { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<UserAccount> UserAccounts { get; set; }
    
        public virtual ObjectResult<TableRef_Result> TableRef(string table)
        {
            var tableParameter = table != null ?
                new ObjectParameter("table", table) :
                new ObjectParameter("table", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TableRef_Result>("TableRef", tableParameter);
        }
    
        public virtual ObjectResult<sp_ProjectTasks_Result> sp_ProjectTasks(Nullable<int> companyId, Nullable<int> projectId, Nullable<int> employeeId)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ProjectTasks_Result>("sp_ProjectTasks", companyIdParameter, projectIdParameter, employeeIdParameter);
        }
    
        public virtual ObjectResult<sp_CompanyTasks_Result> sp_CompanyTasks(Nullable<int> companyId, string projectIds, string empId, Nullable<int> notInEmpList, Nullable<int> notInProjectList, string statusId, string priorityId, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, string taskName, Nullable<System.DateTime> fromEndDate, Nullable<System.DateTime> toEndDate)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var projectIdsParameter = projectIds != null ?
                new ObjectParameter("ProjectIds", projectIds) :
                new ObjectParameter("ProjectIds", typeof(string));
    
            var empIdParameter = empId != null ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(string));
    
            var notInEmpListParameter = notInEmpList.HasValue ?
                new ObjectParameter("notInEmpList", notInEmpList) :
                new ObjectParameter("notInEmpList", typeof(int));
    
            var notInProjectListParameter = notInProjectList.HasValue ?
                new ObjectParameter("notInProjectList", notInProjectList) :
                new ObjectParameter("notInProjectList", typeof(int));
    
            var statusIdParameter = statusId != null ?
                new ObjectParameter("StatusId", statusId) :
                new ObjectParameter("StatusId", typeof(string));
    
            var priorityIdParameter = priorityId != null ?
                new ObjectParameter("PriorityId", priorityId) :
                new ObjectParameter("PriorityId", typeof(string));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var taskNameParameter = taskName != null ?
                new ObjectParameter("taskName", taskName) :
                new ObjectParameter("taskName", typeof(string));
    
            var fromEndDateParameter = fromEndDate.HasValue ?
                new ObjectParameter("FromEndDate", fromEndDate) :
                new ObjectParameter("FromEndDate", typeof(System.DateTime));
    
            var toEndDateParameter = toEndDate.HasValue ?
                new ObjectParameter("ToEndDate", toEndDate) :
                new ObjectParameter("ToEndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CompanyTasks_Result>("sp_CompanyTasks", companyIdParameter, projectIdsParameter, empIdParameter, notInEmpListParameter, notInProjectListParameter, statusIdParameter, priorityIdParameter, fromDateParameter, toDateParameter, taskNameParameter, fromEndDateParameter, toEndDateParameter);
        }
    
        public virtual ObjectResult<sp_TotalEmployeeTasks_Result> sp_TotalEmployeeTasks(Nullable<int> companyId, string empIds, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate, Nullable<System.DateTime> fromEndDate, Nullable<System.DateTime> toEndDate)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var empIdsParameter = empIds != null ?
                new ObjectParameter("EmpIds", empIds) :
                new ObjectParameter("EmpIds", typeof(string));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("FromDate", fromDate) :
                new ObjectParameter("FromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            var fromEndDateParameter = fromEndDate.HasValue ?
                new ObjectParameter("FromEndDate", fromEndDate) :
                new ObjectParameter("FromEndDate", typeof(System.DateTime));
    
            var toEndDateParameter = toEndDate.HasValue ?
                new ObjectParameter("ToEndDate", toEndDate) :
                new ObjectParameter("ToEndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TotalEmployeeTasks_Result>("sp_TotalEmployeeTasks", companyIdParameter, empIdsParameter, fromDateParameter, toDateParameter, fromEndDateParameter, toEndDateParameter);
        }
    
        public virtual ObjectResult<sp_Attendance_Result> sp_Attendance(Nullable<int> companyId, Nullable<int> employeeId, Nullable<System.DateTime> fromDate, Nullable<System.DateTime> todate)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var employeeIdParameter = employeeId.HasValue ?
                new ObjectParameter("EmployeeId", employeeId) :
                new ObjectParameter("EmployeeId", typeof(int));
    
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var todateParameter = todate.HasValue ?
                new ObjectParameter("todate", todate) :
                new ObjectParameter("todate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Attendance_Result>("sp_Attendance", companyIdParameter, employeeIdParameter, fromDateParameter, todateParameter);
        }
    
        public virtual ObjectResult<sp_EmployeePerformanceReport_Result> sp_EmployeePerformanceReport(Nullable<int> companyId, Nullable<System.DateTime> periodStart, Nullable<System.DateTime> periodEnd)
        {
            var companyIdParameter = companyId.HasValue ?
                new ObjectParameter("CompanyId", companyId) :
                new ObjectParameter("CompanyId", typeof(int));
    
            var periodStartParameter = periodStart.HasValue ?
                new ObjectParameter("PeriodStart", periodStart) :
                new ObjectParameter("PeriodStart", typeof(System.DateTime));
    
            var periodEndParameter = periodEnd.HasValue ?
                new ObjectParameter("PeriodEnd", periodEnd) :
                new ObjectParameter("PeriodEnd", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_EmployeePerformanceReport_Result>("sp_EmployeePerformanceReport", companyIdParameter, periodStartParameter, periodEndParameter);
        }
    }
}
