//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogGeneral
    {
        public int LogID { get; set; }
        public int ActionID { get; set; }
        public System.DateTime ActionTime { get; set; }
        public string Value { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<bool> IsCompany { get; set; }
        public Nullable<int> ControllerID { get; set; }
    
        public virtual ControllerName ControllerName { get; set; }
        public virtual Company Company { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
