//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int ID { get; set; }
        public int SenderType { get; set; }
        public int FromInstanceID { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual UserType UserType { get; set; }
    }
}
