//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationCollection
    {
        public int ID { get; set; }
        public int InstanceID { get; set; }
        public int UserTypeID { get; set; }
        public bool IsSeen { get; set; }
        public Nullable<System.DateTime> SeenDate { get; set; }
        public int NotificationID { get; set; }
    
        public virtual Notification Notification { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
