//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public Notification()
        {
            this.NotificationCollections = new HashSet<NotificationCollection>();
        }
    
        public int ID { get; set; }
        public string LinkToGo { get; set; }
        public string Value { get; set; }
        public Nullable<int> MessageID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int NotificationTypeID { get; set; }
    
        public virtual NotificationType NotificationType { get; set; }
        public virtual ICollection<NotificationCollection> NotificationCollections { get; set; }
    }
}
