//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.RecurrenceTasks = new HashSet<RecurrenceTask>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int ProjectID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int CompanyID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<RecurrenceTask> RecurrenceTasks { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual Company Company { get; set; }
    }
}
