//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecurrenceTaskEmp
    {
        public int RecurrenceTaskEmpID { get; set; }
        public Nullable<int> RecurrenceTaskID { get; set; }
        public Nullable<int> EmpID { get; set; }
    
        public virtual RecurrenceTask RecurrenceTask { get; set; }
    }
}
