//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecurrenceTask
    {
        public RecurrenceTask()
        {
            this.RecurrenceTaskEmps = new HashSet<RecurrenceTaskEmp>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int RecurrenceTaskID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Summary { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> RecurrenceTypeID { get; set; }
        public Nullable<System.DateTime> StartRec { get; set; }
        public Nullable<System.DateTime> EndRec { get; set; }
        public string RecValue { get; set; }
        public Nullable<int> CompanyID { get; set; }
    
        public virtual RecurrenceType RecurrenceType { get; set; }
        public virtual ICollection<RecurrenceTaskEmp> RecurrenceTaskEmps { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual Project Project { get; set; }
    }
}
