//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int SettingID { get; set; }
        public string ServerName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int PortNo { get; set; }
        public string FromEmail { get; set; }
        public bool SSL { get; set; }
        public string FacebookURL { get; set; }
        public string TwitterURL { get; set; }
        public string YouTubeURL { get; set; }
        public int OnlineVisiter { get; set; }
        public int VisitorCounter { get; set; }
        public string ContactUsResponsableEmail { get; set; }
    }
}
