//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.Attachments = new HashSet<Attachment>();
            this.TaskComments = new HashSet<TaskComment>();
            this.TaskLogs = new HashSet<TaskLog>();
            this.TaskTLogs = new HashSet<TaskTLog>();
        }
    
        public int TaskID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Summary { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<decimal> ExpectedTime { get; set; }
        public Nullable<int> TimeUnitID { get; set; }
        public Nullable<decimal> ActualTime { get; set; }
        public Nullable<int> EmpID { get; set; }
        public int CompanyID { get; set; }
        public bool IsArchived { get; set; }
        public int PriorityID { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeliverDate { get; set; }
        public Nullable<bool> IsRecurrence { get; set; }
        public Nullable<int> RecurrenceTaskID { get; set; }
        public string BriefTaskName { get; set; }
    
        public virtual ICollection<Attachment> Attachments { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual RecurrenceTask RecurrenceTask { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<TaskComment> TaskComments { get; set; }
        public virtual ICollection<TaskLog> TaskLogs { get; set; }
        public virtual ICollection<TaskTLog> TaskTLogs { get; set; }
        public virtual Project Project { get; set; }
        public virtual TimeUnit TimeUnit { get; set; }
        public virtual Company Company { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
