//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskLog
    {
        public int TaskLogID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public System.DateTime LogDate { get; set; }
        public string Value { get; set; }
        public bool IsFromCompany { get; set; }
        public Nullable<int> CurrentPriority { get; set; }
        public Nullable<int> CurrentStatus { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
