//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskTLog
    {
        public int TaskTLogID { get; set; }
        public int TaskID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public int StatusID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<decimal> TimeCount { get; set; }
        public Nullable<int> TimUnitID { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Task Task { get; set; }
        public virtual TimeUnit TimeUnit { get; set; }
    }
}
