//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskComment
    {
        public int TaskCommentID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Comment { get; set; }
        public bool IsFromCompany { get; set; }
        public int TaskID { get; set; }
        public int CommentStatusId { get; set; }
        public Nullable<int> EmpID { get; set; }
    
        public virtual CommentStatu CommentStatu { get; set; }
        public virtual Task Task { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
