//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeUnit
    {
        public TimeUnit()
        {
            this.Tasks = new HashSet<Task>();
            this.TaskTLogs = new HashSet<TaskTLog>();
            this.TimeUnit1 = new HashSet<TimeUnit>();
        }
    
        public int TimeUnitID { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> ConversionFactor { get; set; }
    
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<TaskTLog> TaskTLogs { get; set; }
        public virtual ICollection<TimeUnit> TimeUnit1 { get; set; }
        public virtual TimeUnit TimeUnit2 { get; set; }
    }
}
