//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<bool> IsCompany { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public Nullable<bool> IsTelesak { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
