//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserType
    {
        public UserType()
        {
            this.Messages = new HashSet<Message>();
            this.NotificationCollections = new HashSet<NotificationCollection>();
            this.SIGNAL_R_SESSION = new HashSet<SIGNAL_R_SESSION>();
            this.UserAccounts = new HashSet<UserAccount>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<NotificationCollection> NotificationCollections { get; set; }
        public virtual ICollection<SIGNAL_R_SESSION> SIGNAL_R_SESSION { get; set; }
        public virtual ICollection<UserAccount> UserAccounts { get; set; }
    }
}
