//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeekEnd
    {
        public int WeekEndID { get; set; }
        public int CompanyID { get; set; }
        public int WeekEndDay { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
